site_name: My Recipes
nav:
    - Home: index.md
    - Teas: 
        - Kombucha: /recipes/kombucha
    - About: about.md
theme:
    name: 'material'
    palette:
        primary: 'Deep Purple'
        accent: 'Purple'