site_name: 'My Recipes'
site_description: 'A wiki for recipes'
site_favicon: img/favicon.ico

nav:
    - Home: index.md
    - Brewing: 
        - Kombucha: 'recipes/kombucha'
    - Cooking:
        - Mac & Cheese: 'recipes/mac-n-cheese'
    - About: about.md

theme:
    name: 'material'
    custom_dir: custom_dir/
    language: 'en'
    palette:
        primary: 'Deep Purple'
        accent: 'Purple'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

copyright: 'Copyright &copy; 2019 Julian Hernandez'