site_name: 'My Recipes'
site_description: 'A wiki for recipes'
site_author: 'Julian Hernandez'

nav:
    - Home: index.md
    - Brewing: 
        - Kombucha: 'recipes/kombucha'
    - Cooking:
        - Mac & Cheese: 'recipes/mac-n-cheese'
    - Locations:
        - Van Huzen: 'locations/van-huzen'
    - About: about.md

extra_javascript: 
    - scripts/maps.js

theme:
    name: 'material'
    language: 'en'
    favicon: favicon.ico
    palette:
        primary: 'Deep Purple'
        accent: 'Purple'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

copyright: 'Copyright &copy; 2019 Julian Hernandez'